version: "3"

services:
  backend:
    build:
      context: ./express
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./react
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
